import { Panel } from "@/components/panel";
import { requireUser } from "@/lib/auth";
import { getWorkspaceContext } from "@/lib/workspace";
import { AlertTriangle, Info } from "lucide-react";

const AUTO_TRACE_RE = /^TRC-\d{5}$/;

function isAutoGenerated(traces: Array<{ traceId: string }>) {
  if (!traces.length) return false;
  return traces.every((t) => AUTO_TRACE_RE.test(t.traceId));
}

export default async function FlowAnalyticsPage({
  params,
}: {
  params: Promise<{ workspaceId: string; slug: string }>;
}) {
  const user = await requireUser();
  const { workspaceId, slug } = await params;
  const { metrics, records } = await getWorkspaceContext(workspaceId, slug, user.id);

  const noRealTraces = isAutoGenerated(metrics.busiestTraces);

  // Build error breakdown by application (useful alternative when no real traces)
  const errorsByApp = records
    .filter((r) => r.level === "ERROR")
    .reduce<Record<string, number>>((acc, r) => {
      acc[r.application] = (acc[r.application] || 0) + 1;
      return acc;
    }, {});
  const topErrorApps = Object.entries(errorsByApp)
    .map(([app, count]) => ({ app, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 8);

  // Top repeated error messages (cluster common errors)
  const errorMessages = records
    .filter((r) => r.level === "ERROR" || r.level === "WARN")
    .reduce<Record<string, { count: number; level: string }>>((acc, r) => {
      // Normalise message: strip numbers/IDs for grouping
      const key = r.message.replace(/\b[\da-f-]{6,}\b/gi, "?").slice(0, 80);
      acc[key] = acc[key] || { count: 0, level: r.level };
      acc[key].count += 1;
      return acc;
    }, {});
  const topErrors = Object.entries(errorMessages)
    .map(([msg, { count, level }]) => ({ msg, count, level }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 10);

  return (
    <div className="space-y-6">
      <header>
        <div className="badge">
          <span className="h-2 w-2 rounded-full bg-cyan-300 animate-pulse" /> Flow analytics
        </div>
        <h1 className="mt-4 text-4xl font-semibold tracking-tight md:text-5xl">
          Trace and dependency hotspots
        </h1>
        <p className="mt-4 max-w-3xl text-sm leading-7 text-slate-400 md:text-base">
          See which traces are busiest and which applications are slowest based on your uploaded logs.
        </p>
      </header>

      {/* Real traces */}
      {!noRealTraces && (
        <div className="grid gap-5 xl:grid-cols-2">
          <Panel className="p-5 md:p-6">
            <div className="text-lg font-semibold">Busiest traces</div>
            <div className="mt-1 text-xs text-slate-400 mb-5">Real trace IDs extracted from log data</div>
            <div className="space-y-3">
              {metrics.busiestTraces.map((item, i) => (
                <div key={item.traceId} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                  <span className="w-5 text-xs text-slate-500 font-mono shrink-0">#{i + 1}</span>
                  <div className="flex-1 min-w-0">
                    <div className="truncate font-mono text-sm text-cyan-300">{item.traceId}</div>
                    <div className="mt-0.5 text-xs text-slate-400">Trace occurrences in uploaded data</div>
                  </div>
                  <div className="text-lg font-semibold shrink-0">{item.count}</div>
                </div>
              ))}
              {!metrics.busiestTraces.length && (
                <div className="text-sm text-slate-400">Upload logs to calculate trace hot paths.</div>
              )}
            </div>
          </Panel>
          <Panel className="p-5 md:p-6">
            <div className="text-lg font-semibold">Slowest applications</div>
            <div className="mt-1 text-xs text-slate-400 mb-5">Average latency per service</div>
            <div className="space-y-3">
              {metrics.slowestApplications.map((item, i) => (
                <div key={item.name} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                  <span className="w-5 text-xs text-slate-500 font-mono shrink-0">#{i + 1}</span>
                  <div className="flex-1 min-w-0">
                    <div className="truncate font-medium">{item.name}</div>
                    <div className="mt-0.5 text-xs text-slate-400">{item.count.toLocaleString()} records analysed</div>
                  </div>
                  <div className={`text-lg font-semibold shrink-0 ${
                    item.avgLatency > 500 ? "text-rose-400" :
                    item.avgLatency > 200 ? "text-amber-300" : "text-emerald-300"
                  }`}>{item.avgLatency} ms</div>
                </div>
              ))}
              {!metrics.slowestApplications.length && (
                <div className="text-sm text-slate-400">Upload logs to identify slow services.</div>
              )}
            </div>
          </Panel>
        </div>
      )}

      {/* Auto-generated traces notice + alternative analytics */}
      {noRealTraces && records.length > 0 && (
        <>
          <div className="flex items-start gap-3 rounded-2xl border border-amber-400/20 bg-amber-400/10 p-4 text-sm text-amber-200">
            <Info className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" />
            <div>
              <div className="font-semibold">No real trace IDs found in log data</div>
              <div className="mt-1 text-amber-200/70">
                Your log files do not contain trace ID fields (e.g. <code className="font-mono text-xs bg-amber-400/10 px-1 rounded">traceId</code>,{" "}
                <code className="font-mono text-xs bg-amber-400/10 px-1 rounded">requestId</code>).
                Auto-generated sequential IDs (TRC-00001…) are not meaningful for hotspot analysis.
                Showing alternative breakdowns below instead.
              </div>
            </div>
          </div>

          <div className="grid gap-5 xl:grid-cols-2">
            {/* Slowest apps */}
            <Panel className="p-5 md:p-6">
              <div className="text-lg font-semibold">Slowest applications</div>
              <div className="mt-1 text-xs text-slate-400 mb-5">Average latency per service across all uploads</div>
              <div className="space-y-3">
                {metrics.slowestApplications.map((item, i) => (
                  <div key={item.name} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                    <span className="w-5 text-xs text-slate-500 font-mono shrink-0">#{i + 1}</span>
                    <div className="flex-1 min-w-0">
                      <div className="truncate font-medium">{item.name}</div>
                      <div className="mt-0.5 text-xs text-slate-400">{item.count.toLocaleString()} records</div>
                    </div>
                    <div className={`text-lg font-semibold shrink-0 ${
                      item.avgLatency > 500 ? "text-rose-400" :
                      item.avgLatency > 200 ? "text-amber-300" : "text-emerald-300"
                    }`}>{item.avgLatency} ms</div>
                  </div>
                ))}
                {!metrics.slowestApplications.length && (
                  <div className="text-sm text-slate-400">No latency data found.</div>
                )}
              </div>
            </Panel>

            {/* Errors by app */}
            <Panel className="p-5 md:p-6">
              <div className="flex items-center gap-2">
                <AlertTriangle className="h-4 w-4 text-rose-400" />
                <div className="text-lg font-semibold">Errors by application</div>
              </div>
              <div className="mt-1 text-xs text-slate-400 mb-5">Which services are generating the most errors</div>
              <div className="space-y-3">
                {topErrorApps.map((item, i) => (
                  <div key={item.app} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                    <span className="w-5 text-xs text-slate-500 font-mono shrink-0">#{i + 1}</span>
                    <div className="flex-1 truncate font-medium">{item.app}</div>
                    <div className="text-lg font-semibold text-rose-400 shrink-0">{item.count.toLocaleString()}</div>
                    <div className="text-xs text-slate-500 shrink-0">errors</div>
                  </div>
                ))}
                {!topErrorApps.length && (
                  <div className="flex items-center gap-2 text-sm text-emerald-300">
                    <span>✓</span> No errors found in log data
                  </div>
                )}
              </div>
            </Panel>
          </div>

          {/* Top repeated error messages */}
          {topErrors.length > 0 && (
            <Panel className="p-5 md:p-6">
              <div className="text-lg font-semibold">Top repeated error/warn messages</div>
              <div className="mt-1 text-xs text-slate-400 mb-5">
                Most frequent error and warning messages across all uploads (IDs/hashes normalised)
              </div>
              <div className="space-y-2">
                {topErrors.map((item, i) => (
                  <div key={i} className="flex items-start gap-3 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3">
                    <span className="w-5 shrink-0 text-xs text-slate-500 font-mono mt-0.5">#{i + 1}</span>
                    <span className={`shrink-0 mt-0.5 inline-flex rounded-lg px-2 py-0.5 text-[10px] font-semibold ring-1 ${
                      item.level === "ERROR"
                        ? "text-rose-400 bg-rose-400/10 ring-rose-400/30"
                        : "text-amber-300 bg-amber-400/10 ring-amber-400/30"
                    }`}>{item.level}</span>
                    <div className="flex-1 min-w-0">
                      <div className="truncate text-sm text-slate-200" title={item.msg}>{item.msg}</div>
                    </div>
                    <div className="shrink-0 text-right">
                      <div className="font-semibold text-slate-200">{item.count.toLocaleString()}</div>
                      <div className="text-[10px] text-slate-500">occurrences</div>
                    </div>
                  </div>
                ))}
              </div>
            </Panel>
          )}
        </>
      )}

      {records.length === 0 && (
        <Panel className="p-10 text-center text-sm text-slate-400">
          Upload log files to see flow analytics and trace hotspot data.
        </Panel>
      )}
    </div>
  );
}
